'''

Script to plot the band structure along high symmetry lines of a hexagonal lattice, 
i.e. along the k-points gamma, M, K, gamma.
Can be modified to accommodate different k-points.

Required files in the directory (as generated by vasp): EIGENVAL, DOSCAR

'''

import sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

#set font size of plot labels
matplotlib.rcParams.update({'font.size':18})

title = sys.argv[1]

f = open('EIGENVAL','r')
f2 = open('DOSCAR','r')


lines = f.readlines()
nbands = int(lines[5].split()[2])

bands = {}
#structure of bands dictionary:
#    key: band number
#    value: [(x1,y1),(x2,y2),...,(xn,yn)] where the tuples are the coordinates to plot

#initialize arrays for each dictionary entry
for i in range(nbands):
    bands[i] = []    

#get Fermi energy
f2lines=f2.readlines()
ef = [float(k) for k in f2lines[5].split()][3]


#initialize placeholders for x-values
current_x = 0.
prev = 0.

for line in lines[6:]:
    floats = [float(x) for x in line.split()]
    if len(floats)==4:
        if (floats[0] >= current_x) and floats[1]==0:
            #along the path of gamma to M
	    current_x = floats[0]
	    prev = floats[1]

	elif (floats[1] > prev):
	    #along the path of M to K
	    current_x = 0.5 + np.sqrt((floats[0]-0.5)**2 + (floats[1])**2)
	    prev = floats[1]

	else:
	     #along the path of K to gamma
	    current_x = 0.5 + np.sqrt(5)/6 + np.sqrt((floats[0]-0.33333)**2 + (floats[1]-0.33333)**2)
       
    if len(floats)==2:
        n = int(floats[0])-1 #n = band number
        bands[n] += [(current_x,floats[1])]


#set figure size
plt.figure(figsize=(7,21))

#begin plotting
for i in range(nbands):
    bands[i] = sorted(bands[i],key=lambda y: y[0])
    plt.plot([a[0] for a in bands[i]], [a[1] for a in bands[i]])

#draw lines to indicate k-points and Fermi energy
plt.axhline(ef,color='black',label="$E_f$")
plt.axvline(0.5,color='gray',label="M")
plt.axvline(0.5+np.sqrt(5)/6,color='gray',label="K")

#label the graph
xmax=max([a[0] for a in bands[1]])
plt.text(xmax,ef,"$E_f$",fontsize=22)
plt.text(0.487,ef-2.15,"$M$",fontsize=24)
plt.text(0.5+np.sqrt(5)/6-0.009,ef-2.15,"$K$",fontsize=24)
plt.text(-0.003,ef-2.15,"$\Gamma$",fontsize=24)
plt.text(xmax-0.003,ef-2.15,"$\Gamma$",fontsize=24)
plt.ylabel("eV")
plt.title(title)
plt.tick_params(axis='x',which='both',bottom='off',labelbottom='off')

#limit the graph such that you only see bands close to the Fermi level
plt.xlim(0,xmax)
plt.ylim(ef-2,ef+2)

f.close()
f2.close()

#plt.savefig("/home/" + title + "_band.png")

plt.show()
